---
title: "Explaining regression models with localModel package"
author: "Mateusz Staiak"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Explaining regression models with localModel package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r pkgs}
library(DALEX)
library(localModel)
library(randomForest)
data('apartments')
data('apartmentsTest')

apartments <- dplyr::mutate_all(apartments, 
                                function(x) {
                                  if(dplyr::n_distinct(x) < 10) as.factor(as.character(x))
                                  else x
                                })
apartmentsTest <- dplyr::mutate_all(apartmentsTest, 
                                function(x) {
                                  if(dplyr::n_distinct(x) < 10) as.factor(as.character(x))
                                  else x
                                })


mrf <- randomForest(m2.price ~., data = apartments, ntree = 50)

explainer <- DALEX::explain(model = mrf,
                            data = apartmentsTest[, -1],
                            y = apartmentsTest$m2.price)
new_observation <- apartmentsTest[5, -1]

model_lok <- individual_surrogate_model(explainer, new_observation,
                                        size = 500, grid_points = 100,
                                        smoothness = NULL)
plot(model_lok)
```

